### ISSUE TITLE
Conflicting methods `min` and `max` on `Set` and `Map`

### ISSUE THREAD

**Issue by KodrAus** [apasel422/tree#23]
In https://github.com/rust-lang/rust/pull/42496, methods `min` and `max` were added to the `Ord` trait.

These methods are shadowing the inherent `min` and `max` on `Set` and `Map` (see: https://github.com/rust-lang/rust/issues/43682), and unfortunately don't have the same signature, and there doesn't seem to be a single obvious fix for `tree`.

The easiest thing to do is rename `Map.min/max` and `Set.min/max` or just remove those methods. It might also be possible to design around the issue by exposing the `min` and `max` functions on a type that doesn't implement `Ord`. Maybe something like `Map.find().min()` and `Map.find_mut().min()`?

**Comment by KodrAus** [comment]
cc: @apasel422

**Comment by apasel422** [comment]
I'd accept a pull request that renames the `min` methods to `first` and the `max` methods to last.

**Comment by KodrAus** [comment]
Would you want to keep the naming consistent for `remove_min`, `min_entry` etc?

**Comment by apasel422** [comment]
Those should be changed as well.

**Comment by KodrAus** [comment]
No worries, I'll submit a PR shortly :+1:
